minVersion: "0.13.2"
github:
  owner: getsentry
  repo: symbolic
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

preReleaseCommand: bash scripts/bump-version
targets:
  - name: crates
  - name: pypi
  - name: github
requireNames:
  - /^symbolic-.*-py2.py3-none-macosx_10_15_x86_64.whl$/
  - /^symbolic-.*-py2.py3-none-macosx_11_0_arm64.whl$/
  - /^symbolic-.*-py2\.py3-none-.*manylinux2010_i686.*\.whl$/
  - /^symbolic-.*-py2\.py3-none-.*manylinux2010_x86_64\.whl$/
  - /^symbolic-.*-py2\.py3-none-.*manylinux2014_aarch64\.whl$/
  - /^symbolic-.*.zip$/
