minVersion: "0.34.1"
github:
  owner: getsentry
  repo: symbolic
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

preReleaseCommand: bash scripts/bump-version
targets:
  - name: crates
  - name: pypi
  - name: github
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
requireNames:
  - /^symbolic-.*-py2.py3-none-macosx_10_15_x86_64.whl$/
  - /^symbolic-.*-py2.py3-none-macosx_11_0_arm64.whl$/
  - /^symbolic-.*-py2.py3-none-manylinux_2_28_aarch64.whl$/
  - /^symbolic-.*-py2.py3-none-manylinux_2_28_x86_64.whl$/
  - /^symbolic-.*.tar.gz$/
