---
minVersion: "0.9.0"
github:
  owner: getsentry
  repo: symbolic
preReleaseCommand: bash scripts/bump-version
targets:
  # - name: crates
  - name: pypi
  - name: github
changelogPolicy: simple
requireNames:
  - /^symbolic-.*-py2.py3-none-macosx_10_13_x86_64.whl$/
  - /^symbolic-.*-py2.py3-none-manylinux1_i686.whl$/
  - /^symbolic-.*-py2.py3-none-manylinux1_x86_64.whl$/
  - /^symbolic-.*.zip$/
