---
github:
  owner: getsentry
  repo: symbolic
preReleaseCommand: bash scripts/bump-version
targets:
  # temporarily removed because of git dependencies
  #  - name: crates
  - name: pypi
  - name: github
