#!/bin/sh

FLAGS=""

while : ; do
    case "$1" in
    "--release")
        FLAGS="$FLAGS --release"
        ;;
    "--trace")
        export RUST_BACKTRACE=1
        ;;
    *)
        break
        ;;
    esac
    shift
done

if [ $# -lt 1 ]; then
    echo "usage: $0 [--release] <example> [args...]"
    exit
fi

EXAMPLE="$1";
shift

set -x
cargo run --quiet --all-features --package $EXAMPLE $FLAGS -- "$@"
