[package]
name = "smcache_debug"
version = "9.1.1"
authors = ["Sentry <hello@sentry.io>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.32"
clap = "3.1.0"
symbolic = { path = "../../symbolic", features = ["smcache"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
