[package]
name = "smcache_debug"
version = "9.0.0"
edition = "2018"
publish = false

[dependencies]
symbolic = { path = "../../symbolic", features = ["smcache"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
