//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Sentry.Samples.Console.Basic")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("9.8.7.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("9.8.7")]
[assembly: System.Reflection.AssemblyProductAttribute("Sentry.Samples.Console.Basic")]
[assembly: System.Reflection.AssemblyTitleAttribute("Sentry.Samples.Console.Basic")]
[assembly: System.Reflection.AssemblyVersionAttribute("9.8.7.0")]

// Generated by the MSBuild WriteCodeFragment class.

