name: Periodic CI

on:
  schedule:
    - cron: "11 7 * * 1,4"
  workflow_dispatch:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    fail-fast: false
    strategy:
      matrix:
        rust: [nightly, beta]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: clippy

      - name: Run clippy ${{ matrix.rust }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --workspace --tests --examples -- -D clippy::all

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features
